### ISSUE TITLE
undefined local variable or method `cp'

### ISSUE THREAD

**Issue by thomthom** [Aerilius/sketchup-console-plus#30]
```rb
Error: #<NameError: undefined local variable or method `cp' for #<AE::ConsolePlugin::EntityHighlightTool:0x0000028c31d83618>>
C:/Users/Thomas/AppData/Roaming/SketchUp/SketchUp 2020/SketchUp/Plugins/ae_console/features/entity_highlight_tool.rb:309:in `block in draw'
C:/Users/Thomas/AppData/Roaming/SketchUp/SketchUp 2020/SketchUp/Plugins/ae_console/features/entity_highlight_tool.rb:252:in `each'
C:/Users/Thomas/AppData/Roaming/SketchUp/SketchUp 2020/SketchUp/Plugins/ae_console/features/entity_highlight_tool.rb:252:in `draw'
C:/Users/Thomas/AppData/Roaming/SketchUp/SketchUp 2020/SketchUp/Plugins/ae_console/features/feature_select_entity.rb:220:in `draw'
```

I only glanced at the code, but I think `cp` should be `center`:

https://github.com/Aerilius/sketchup-console-plus/blob/e58d9916604ea08e9abb4cf212e11a0c0e57891b/src/ae_console/features/entity_highlight_tool.rb#L307-L309

**Comment by Aerilius** [comment]
That's right.
