### ISSUE TITLE
Not starting in Sketchup 2024

### ISSUE THREAD

**Issue by hanneseklund** [Aerilius/sketchup-console-plus#44]
```
Extension Errors Report
SketchUp: 24.0.484
OS: Windows 10 
Ruby: 3.2.2

Extension: Ruby Console+ (3.1.7)
Error: TypeError (allocator undefined for #<Class:0x0000018f595f9f80>)
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console/core.rb:125:in `new'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console/core.rb:125:in `initialize_plugin'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console/core.rb:213:in `<module:ConsolePlugin>'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console/core.rb:3:in `<module:AE>'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console/core.rb:1:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2024/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2024/Tools/extensions.rb:197:in `load'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console.rb:26:in `register_extension'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console.rb:26:in `<module:ConsolePlugin>'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console.rb:7:in `<module:AE>'
C:/Users/hannes/AppData/Roaming/SketchUp/SketchUp 2024/SketchUp/Plugins/ae_console.rb:5:in `<top (required)>'
```

**Comment by manulykebe** [comment]
forked new version, compatible with Sketchup 2024:
https://github.com/manulykebe/sketchup-console-plus

**Comment by thomthom** [comment]
The latest version in source is 3.1.7 which works fine with SU2024. The latest under the Release page is out of date.

@Aerilius are you interested in assistance in mantaining this repo? We can assist in updating the Release section and even get it uploaded to Extension Warehouse.

**Comment by Aerilius** [comment]
I've updated the repository with my fixes and built a new release. It should work now in the current version of SketchUp.

> and even get it uploaded to Extension Warehouse.

I have now a GitHub Action for building the .rbz, I don't know if it is possible to automate the submission as well.

**Comment by thomthom** [comment]
Thank you! 

I was using your console in a presentation at this year's Basecamp. Found that the attendees wasn't able to run it, which had me puzzled. I only just realized now that I was 3 patches ahead of them because I was running the extension from source (I had modified it for the presentation: https://github.com/thomthom/sketchup-console-plus/commits/dev/snippets/)

Atm there is no EW API, and the Trimble ID login system prevents bots (automation scripts) from signing in.

We would love for this to be on EW though, would make it much more accessible. (The presentation Chris F and I did was showing people that never touched code to not be afraid of code. And that Ruby and the SU API is a lot easier than they expect. Console+ fit well into that as we introduced the audience to tinkering.)
